apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bid-trader
  labels:
    app: bid-trader
spec:
  template:
    metadata:
      labels:
        app: bid-trader
    spec:
      containers:
        - name: trader-worker
          image: gcr.io/bidcache/bidtrader:51
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "768Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: dburl
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: ENABLE_NEWRELIC
              value: "true"
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-credentials
                  key: license
            - name: USE_SSL
              value: "true"
            - name: ESB_AMQ_ADDRESS
              value: esb-svc.default.svc.cluster.local
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=bidcache:us-central1:opportunity-trader=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
